import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import Header from "|client-extension/components/header";
import Provider from "|client-extension/components/provider";
import { getServerSession } from "next-auth";
import { options } from "|client-extension/lib/auth";
import React, { PropsWithChildren } from "react";

import "|client-extension/app/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function RootLayout({ children }: PropsWithChildren) {
  const session = await getServerSession(options);
  return (
    <html lang="en">
      <body className={clsx(inter.className, "max-w-[680px] mx-auto w-full")}>
        <main>
          <Provider session={session}>
            <Header />
          </Provider>
          {children}
        </main>
      </body>
    </html>
  );
}

export default RootLayout;
